environment:
  matrix:
    - GENERATOR: "Visual Studio 12 2013"
      PLATFORM: MSVC
      CONFIG: Debug

    - GENERATOR: "Visual Studio 12 2013"
      PLATFORM: MSVC
      CONFIG: Release

    - GENERATOR: "Visual Studio 12 2013 Win64"
      PLATFORM: MSVC
      CONFIG: Debug

    - GENERATOR: "Visual Studio 12 2013 Win64"
      PLATFORM: MSVC
      CONFIG: Release

    - GENERATOR: "Visual Studio 14 2015"
      PLATFORM: MSVC
      CONFIG: Debug

    - GENERATOR: "Visual Studio 14 2015"
      PLATFORM: MSVC
      CONFIG: Release

    - GENERATOR: "Visual Studio 14 2015 Win64"
      PLATFORM: MSVC
      CONFIG: Debug

    - GENERATOR: "Visual Studio 14 2015 Win64"
      PLATFORM: MSVC
      CONFIG: Release

    - GENERATOR: "MinGW Makefiles"
      PLATFORM: MinGW-w64
      CONFIG: Debug

    - GENERATOR: "MinGW Makefiles"
      PLATFORM: MinGW-w64
      CONFIG: Release

    - GENERATOR: "MinGW Makefiles"
      PLATFORM: CLang
      CONFIG: Debug

    - GENERATOR: "MinGW Makefiles"
      PLATFORM: CLang
      CONFIG: Release

install:
  - if [%PLATFORM%]==[MinGW-w64] rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"
  - ps: If ($Env:PLATFORM -eq 'MinGW-w64') { (New-Object Net.WebClient).DownloadFile("http://downloads.sourceforge.net/mingw-w64/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/4.8.5/threads-win32/sjlj/i686-4.8.5-release-win32-sjlj-rt_v4-rev0.7z", "$env:APPVEYOR_BUILD_FOLDER\mw32.7z") }
  - if [%PLATFORM%]==[MinGW-w64] 7z x -oC:\ mw32.7z > NUL
  - if [%PLATFORM%]==[MinGW-w64] set PATH=C:\mingw32\bin;%PATH%
  - if [%PLATFORM%]==[CLang] rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"
  - ps: If ($Env:PLATFORM -eq 'CLang') { (New-Object Net.WebClient).DownloadFile("http://releases.llvm.org/4.0.0/LLVM-4.0.0-win32.exe", "$env:APPVEYOR_BUILD_FOLDER\llvm32.exe") }
  - if [%PLATFORM%]==[CLang] 7z x -oC:\llvm32 llvm32.exe > NUL
  - if [%PLATFORM%]==[CLang] set PATH=C:\llvm32\bin;%PATH%
  - if [%PLATFORM%]==[CLang] set CC=C:\llvm32\bin\clang.exe
  - if [%PLATFORM%]==[CLang] set CXX=C:\llvm32\bin\clang++.exe

build_script:
  - mkdir build
  - cd build
  - if [%PLATFORM%]==[CLang] cmake -G "%GENERATOR%" -DCLANG=ON ..
  - if [%PLATFORM%]!=[CLang] cmake -G "%GENERATOR%" ..
  - cmake --build . --config "%CONFIG%"
