environment:
  matrix:
    - GENERATOR: "Visual Studio 12 2013"
      PLATFORM: MSVC
      CONFIG: Debug

    - GENERATOR: "Visual Studio 12 2013"
      PLATFORM: MSVC
      CONFIG: Release

    - GENERATOR: "Visual Studio 12 2013 Win64"
      PLATFORM: MSVC
      CONFIG: Debug

    - GENERATOR: "Visual Studio 12 2013 Win64"
      PLATFORM: MSVC
      CONFIG: Release

    - GENERATOR: "Visual Studio 14 2015"
      PLATFORM: MSVC
      CONFIG: Debug

    - GENERATOR: "Visual Studio 14 2015"
      PLATFORM: MSVC
      CONFIG: Release

    - GENERATOR: "Visual Studio 14 2015 Win64"
      PLATFORM: MSVC
      CONFIG: Debug

    - GENERATOR: "Visual Studio 14 2015 Win64"
      PLATFORM: MSVC
      CONFIG: Release

    - GENERATOR: "MinGW Makefiles"
      PLATFORM: MinGW-w64
      CONFIG: Debug

    - GENERATOR: "MinGW Makefiles"
      PLATFORM: MinGW-w64
      CONFIG: Release

install:
  - if [%PLATFORM%]==[MinGW-w64] rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"
  - if [%PLATFORM%]==[MinGW-w64] curl -fsSL -o mw32.7z "https://downloads.sourceforge.net/mingw-w64/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/4.9.3/threads-win32/sjlj/i686-4.9.3-release-win32-sjlj-rt_v4-rev1.7z"
  - if [%PLATFORM%]==[MinGW-w64] 7z x -oC:\ mw32.7z > NUL
  - if [%PLATFORM%]==[MinGW-w64] set PATH=C:\mingw32\bin;%PATH%

build_script:
  - mkdir build
  - cd build
  - cmake -G "%GENERATOR%" ..
  - cmake --build . --config "%CONFIG%"
