image:
  Visual Studio 2015

environment:
  matrix:
    - GENERATOR: "Visual Studio 11 2012"
      PLATFORM: MSVC2012
      CONFIG: Debug

    - GENERATOR: "Visual Studio 11 2012"
      PLATFORM: MSVC2012
      CONFIG: Release

    - GENERATOR: "Visual Studio 12 2013"
      PLATFORM: MSVC
      CONFIG: Debug

    - GENERATOR: "Visual Studio 12 2013"
      PLATFORM: MSVC
      CONFIG: Release

    - GENERATOR: "Visual Studio 12 2013 Win64"
      PLATFORM: MSVC
      CONFIG: Debug

    - GENERATOR: "Visual Studio 12 2013 Win64"
      PLATFORM: MSVC
      CONFIG: Release

    - GENERATOR: "Visual Studio 14 2015"
      PLATFORM: MSVC
      CONFIG: Debug

    - GENERATOR: "Visual Studio 14 2015"
      PLATFORM: MSVC
      CONFIG: Release

    - GENERATOR: "Visual Studio 14 2015 Win64"
      PLATFORM: MSVC
      CONFIG: Debug

    - GENERATOR: "Visual Studio 14 2015 Win64"
      PLATFORM: MSVC
      CONFIG: Release

    - GENERATOR: "MinGW Makefiles"
      PLATFORM: MinGW-w64
      CONFIG: Debug

    - GENERATOR: "MinGW Makefiles"
      PLATFORM: MinGW-w64
      CONFIG: Release

    - GENERATOR: "Visual Studio 14 2015"
      PLATFORM: CLang
      CONFIG: Debug

    - GENERATOR: "Visual Studio 14 2015"
      PLATFORM: CLang
      CONFIG: Release

install:
  - if [%PLATFORM%]==[MinGW-w64] rename "C:\Program Files\Git\usr\bin\sh.exe" "sh2.exe"
  - ps: If ($Env:PLATFORM -eq 'MinGW-w64') { (New-Object Net.WebClient).DownloadFile("http://downloads.sourceforge.net/mingw-w64/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/4.8.5/threads-win32/sjlj/i686-4.8.5-release-win32-sjlj-rt_v4-rev0.7z", "$env:APPVEYOR_BUILD_FOLDER\mw32.7z") }
  - if [%PLATFORM%]==[MinGW-w64] 7z x -oC:\ mw32.7z > NUL
  - if [%PLATFORM%]==[MinGW-w64] set PATH=C:\mingw32\bin;%PATH%
  - if [%PLATFORM%]==[CLang] set PATH="C:\Program Files\LLVM\bin";%PATH%
  - if [%PLATFORM%]==[CLang] clang-cl -v
  - ps: If ($Env:PLATFORM -eq 'MSVC2012') { (New-Object Net.WebClient).DownloadFile("https://download.microsoft.com/download/5/1/6/5169AA1E-D7A4-4DC2-A9AE-0A9DFD2601AB/vc_compilerCTPNov2012.exe", "$env:APPVEYOR_BUILD_FOLDER\vc_compilerCTPNov2012.exe") ; "$env:APPVEYOR_BUILD_FOLDER\vc_compilerCTPNov2012.exe" /install /quiet /norestart }

build_script:
  - mkdir build
  - cd build
  - if [%PLATFORM%]==[CLang] cmake -G "%GENERATOR%" -T"LLVM-vs2014" ..
  - if [%PLATFORM%]==[MSVC2012] cmake -G "%GENERATOR%" -T"v120_CTP_Nov2012" ..
  - if [%PLATFORM%]==[MSVC] cmake -G "%GENERATOR%" ..
  - if [%PLATFORM%]==[MinGW-w64] cmake -G "%GENERATOR%" ..
  - cmake --build . --config "%CONFIG%"
